baseURL = "http://example.org/"
languageCode = "fi"
title = "Hammaslääkäripalvelu Lähteenoja"

[menu]
  [[menu.nav]]
    identifier = "henkilokunta"
    name = "Henkilökunta"
    url = "/henkilokunta/"
    weight = 4
  [[menu.nav]]
    identifier = "palvelut"
    name = "Palvelut"
    url = "/palvelut/"
    weight = 3
  [[menu.nav]]
    identifier = "ota-yhteytta"
    name = "Ota yhteyttä"
    url = "/ota-yhteytta/"
    weight = 2
  [[menu.nav]]
    identifier = "varaa-aika"
    name = "Varaa aika"
    url = "#"
    weight = 1
