baseURL = "/"
languageCode = "fi"
title = "Hammaslääkäripalvelu Lähteenoja"

[menu]
  [[menu.nav]]
    identifier = "henkilokunta"
    name = "Henkilökunta"
    url = "/henkilokunta/"
    weight = 4
  [[menu.nav]]
    identifier = "palvelut"
    name = "Palvelut"
    url = "/palvelut/"
    weight = 3
  [[menu.nav]]
    identifier = "yhteydenotto-ja-ajanvaraus"
    name = "Yhteydenotto ja ajanvaraus"
    url = "/yhteydenotto-ja-ajanvaraus/"
    weight = 2
