backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "content/uploads" # Media files will be stored in the repo under images
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://hammasjuho.fi
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - label: "Sivut"
    name: "pages"
    files:
      - file: content/_index.md
        label: Etusivu
        name: index
        fields:
          - label: Otsikko
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Meta-kuvaus
            name: metaDescription
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Kuva
            name: banner
            required: true
            widget: image
            hint: ""
            default: ""
            allow_multiple: false
          - label: Teksti
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
      - file: content/yhteydenotto-ja-ajanvaraus/_index.md
        label: Yhteydenotto ja ajanvaraus
        name: yhteydenotto-ja-ajanvaraus
        fields:
          - label: Otsikko
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Meta-kuvaus
            name: metaDescription
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Teksti
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
      - file: content/palvelut/_index.md
        label: Palvelut
        name: palvelut
        fields:
          - label: Otsikko
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Meta-kuvaus
            name: metaDescription
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Teksti
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
      - file: content/henkilokunta/_index.md
        label: Henkilökunta
        name: henkilokunta
        fields:
          - label: Otsikko
            name: title
            required: true
            widget: string
            hint: ""
            default: ""
          - label: Meta-kuvaus
            name: metaDescription
            required: true
            widget: text
            hint: ""
            default: ""
          - label: Teksti
            name: body
            required: true
            widget: markdown
            hint: ""
            default: ""
          - label: Henkilö
            name: staff
            widget: list
            hint: ""
            default: ""
            allow_add: true
            fields:
              - label: Nimi
                name: name
                required: true
                widget: string
                hint: ""
                default: ""
              - label: Naama
                name: portrait
                required: true
                widget: image
                hint: ""
                default: ""
                allow_multiple: false
              - label: Kuvaus
                name: description
                required: false
                widget: text
                hint: ""
                default: ""
  - label: "Footer"
    name: "footer"
    files:
      - label: "Footer"
        name: "footer"
        file: "content/headless/footer.md"
        fields: # The fields for each document, usually in front matter
          - label: "Osoite"
            name: "address"
            widget: "string"
          - label: "Sähköposti"
            name: "email"
            widget: "string"
          - label: "Puhelinnumero"
            name: "phone"
            widget: "string"
          - label: "Whatsapp-linkki"
            name: "whatsappLink"
            widget: "string"
      
  